stages:
  - lint
  - test
  - build 

variables:
  image_name: flask-music-app
  image_tag: python-app-1.0

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    
lint:
  image: python:3.11-slim
  stage: lint 
  before_script:
      - pip install ruff
  script:
      - ruff check .

run_tests: 
  image: python:3.11-slim 
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest discover -s tests

build_image:
  image: docker:29.0.0-rc.1-cli
  services:
    - docker:20.10.16-dind
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $docker_user -p $docker_pass
  script:
    - docker build -t
    - docker push 

